twig:
    default_path: '%kernel.project_dir%/templates'
    strict_variables: '%kernel.debug%'
    
    # Optionally, you can define global variables to use in all templates.
    globals:
        bootstrap_css: 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css'
        bootstrap_js: 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js'
