#version: "3"

services:
    db:
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony_app

    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony
        networks:
            - symfony_app

    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony
        ports:
            - 81:80
        networks:
            - symfony_app
        env_file:
            - .env.nginx.local

    react:
        build:
            context: /Applications/web app/ecom-front/  # Path to your React frontend directory
            dockerfile: Dockerfile                     # Explicit Dockerfile reference
        ports:
            - 3001:3000                                # Map port 3001 to container's port 3000
        volumes:
            - /Applications/web app/ecom-front:/app    # Mount the frontend folder/Applications/web app/ecom-front/Dockerfile
            - /app/node_modules                        # Prevents node_modules from being overwritten
        stdin_open: true
        tty: true
        environment:
            - CHOKIDAR_USEPOLLING=true                 # Optional for file change detection
        networks:
            - symfony_app

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: db
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD}
            PMA_ARBITRARY: 1
        ports:
            - 8089:80
        networks:
            - symfony_app

    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"
            - "1026:1025"
        networks:
            - symfony_app

volumes:
    symfony_app_var:
    symfony_app_vendor:
    db_app:

networks:
    symfony_app:
        driver: bridge

